const mongoose = require("mongoose");
const medicineModel = require("./Models/Medicine");
require('dotenv').config();
const URL = process.env.URL;
mongoose.connect(URL, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Generate unique 4-digit codes
function generateUniqueCodes(count) {
  const codes = new Set();
  while (codes.size < count) {
    const code = Math.floor(1000 + Math.random() * 9000);
    codes.add(code);
  }
  return Array.from(codes);
}

const baseMedicines = [
  { name: "Paracetamol", use: "Fever and pain relief", quantity: 30 },
  { name: "Ibuprofen", use: "Anti-inflammatory and pain relief", quantity: 25 },
  { name: "Amoxicillin", use: "Bacterial infections", quantity: 20 },
  {
    name: "Ciprofloxacin",
    use: "Urinary and respiratory infections",
    quantity: 15,
  },
  { name: "Metformin", use: "Type 2 diabetes", quantity: 40 },
  { name: "Omeprazole", use: "Acidity and ulcers", quantity: 35 },
  { name: "Cetirizine", use: "Allergy relief", quantity: 50 },
  { name: "Amlodipine", use: "High blood pressure", quantity: 28 },
  { name: "Losartan", use: "Hypertension", quantity: 18 },
  { name: "ORS Sachets", use: "Dehydration", quantity: 60 },
  { name: "Salbutamol Inhaler", use: "Asthma", quantity: 10 },
  { name: "Ranitidine", use: "Acid reflux", quantity: 32 },
  { name: "Azithromycin", use: "Respiratory infections", quantity: 22 },
  { name: "Vitamin C Tablets", use: "Immunity boost", quantity: 45 },
  { name: "Multivitamins", use: "Nutritional supplement", quantity: 38 },
  { name: "Diclofenac", use: "Muscle and joint pain", quantity: 27 },
  { name: "Hydrocortisone Cream", use: "Skin inflammation", quantity: 12 },
  { name: "Antiseptic Lotion", use: "Wound cleaning", quantity: 20 },
  { name: "Bandages", use: "Wound dressing", quantity: 100 },
  { name: "Thermometer", use: "Measure body temperature", quantity: 5 },
  { name: "Chlorpheniramine", use: "Cold and allergy symptoms", quantity: 36 },
  { name: "Pantoprazole", use: "GERD and acid reflux", quantity: 30 },
  { name: "Dolo 650", use: "Pain and fever", quantity: 55 },
  { name: "Betadine Ointment", use: "Wound antiseptic", quantity: 14 },
  { name: "Erythromycin", use: "Bacterial infections", quantity: 19 },
  { name: "Allegra", use: "Seasonal allergies", quantity: 26 },
  { name: "Loratadine", use: "Allergy symptoms", quantity: 44 },
  { name: "Domperidone", use: "Nausea and vomiting", quantity: 17 },
  { name: "Ondansetron", use: "Anti-nausea", quantity: 23 },
  { name: "Calcium Tablets", use: "Bone strength", quantity: 31 },
  { name: "Iron Tablets", use: "Treats anemia", quantity: 41 },
  { name: "ORS Liquid Bottles", use: "Rehydration", quantity: 29 },
  { name: "Clotrimazole Cream", use: "Fungal infections", quantity: 16 },
  { name: "Miconazole", use: "Yeast infections", quantity: 11 },
  { name: "Neomycin Powder", use: "Wound infection prevention", quantity: 13 },
  { name: "Antacid Tablets", use: "Stomach acidity", quantity: 47 },
  { name: "Glucon-D", use: "Instant energy", quantity: 24 },
  { name: "Zinc Tablets", use: "Boosts immunity", quantity: 33 },
  { name: "B Complex Capsules", use: "Nerve and energy health", quantity: 39 },
  { name: "Levocetirizine", use: "Allergies", quantity: 42 },
  { name: "Naproxen", use: "Pain relief", quantity: 21 },
  { name: "Phenylephrine", use: "Nasal congestion", quantity: 18 },
  { name: "Ivermectin", use: "Parasitic infections", quantity: 34 },
  { name: "Albendazole", use: "Deworming", quantity: 46 },
  { name: "Thyroxine", use: "Thyroid regulation", quantity: 20 },
  { name: "Insulin", use: "Diabetes", quantity: 9 },
  {
    name: "Sodium Chloride IV",
    use: "Hydration and electrolyte balance",
    quantity: 8,
  },
  { name: "Glucose IV", use: "Energy and fluid replenishment", quantity: 10 },
  { name: "Strepsils", use: "Sore throat relief", quantity: 50 },
  { name: "Atorvastatin", use: "Cholesterol control", quantity: 28 },
  { name: "Lisinopril", use: "Blood pressure management", quantity: 34 },
  { name: "Clopidogrel", use: "Prevent blood clots", quantity: 21 },
  { name: "Warfarin", use: "Blood thinner", quantity: 17 },
  { name: "Insulin Glargine", use: "Long-acting insulin", quantity: 12 },
  { name: "Metoprolol", use: "Heart conditions", quantity: 31 },
  { name: "Furosemide", use: "Fluid retention", quantity: 25 },
  { name: "Hydrochlorothiazide", use: "Diuretic", quantity: 29 },
  { name: "Dexamethasone", use: "Inflammation and allergies", quantity: 18 },
  { name: "Prednisolone", use: "Anti-inflammatory steroid", quantity: 20 },
  { name: "Nitroglycerin", use: "Chest pain", quantity: 10 },
  { name: "Bisoprolol", use: "Heart-related problems", quantity: 16 },
  { name: "Atenolol", use: "Lower heart rate", quantity: 22 },
  { name: "Glibenclamide", use: "Type 2 diabetes", quantity: 26 },
  { name: "Pioglitazone", use: "Control blood sugar", quantity: 19 },
  { name: "Rosuvastatin", use: "Lowers cholesterol", quantity: 23 },
  { name: "Esomeprazole", use: "Acid reflux and GERD", quantity: 33 },
  { name: "Lansoprazole", use: "Stomach ulcers", quantity: 21 },
  { name: "Rabeprazole", use: "Acidity", quantity: 32 },
  { name: "Meloxicam", use: "Arthritis pain", quantity: 14 },
  { name: "Ketorolac", use: "Moderate pain relief", quantity: 11 },
  { name: "Tramadol", use: "Severe pain", quantity: 15 },
  { name: "Morphine", use: "Extreme pain", quantity: 9 },
  { name: "Codeine", use: "Pain and cough relief", quantity: 10 },
  { name: "Levofloxacin", use: "Bacterial infections", quantity: 24 },
  { name: "Linezolid", use: "Serious bacterial infections", quantity: 13 },
  { name: "Meropenem", use: "Severe bacterial infections", quantity: 7 },
  { name: "Cefixime", use: "Broad-spectrum antibiotic", quantity: 26 },
  { name: "Ceftriaxone", use: "Infections", quantity: 16 },
  { name: "Cefuroxime", use: "Bacterial diseases", quantity: 19 },
  { name: "Tetracycline", use: "Bacterial infections", quantity: 20 },
  { name: "Doxycycline", use: "Respiratory infections", quantity: 22 },
  { name: "Minocycline", use: "Skin and acne treatment", quantity: 12 },
  { name: "Clindamycin", use: "Anaerobic infections", quantity: 18 },
  { name: "Hydroxychloroquine", use: "Malaria and autoimmune", quantity: 21 },
  { name: "Chloroquine", use: "Malaria", quantity: 17 },
  { name: "Artemether", use: "Malaria treatment", quantity: 14 },
  { name: "Lumefantrine", use: "Combined malaria drug", quantity: 14 },
  { name: "Rifampicin", use: "Tuberculosis", quantity: 27 },
  { name: "Isoniazid", use: "TB treatment", quantity: 28 },
  { name: "Ethambutol", use: "TB antibiotic", quantity: 22 },
  { name: "Pyrazinamide", use: "Tuberculosis", quantity: 20 },
  { name: "Montelukast", use: "Asthma and allergies", quantity: 35 },
  { name: "Theophylline", use: "Bronchodilator", quantity: 19 },
  { name: "Beclomethasone Inhaler", use: "Asthma prevention", quantity: 11 },
  { name: "Formoterol", use: "COPD and asthma", quantity: 13 },
  { name: "Budesonide", use: "Inflammatory conditions", quantity: 15 },
  { name: "Fluticasone", use: "Allergic rhinitis", quantity: 20 },
  { name: "Salbutamol Syrup", use: "Child asthma", quantity: 16 },
  { name: "Xylometazoline", use: "Nasal decongestion", quantity: 25 },
  { name: "Naphazoline", use: "Eye redness", quantity: 14 },
  { name: "Tobramycin Eye Drops", use: "Eye infection", quantity: 18 },
  { name: "Timolol", use: "Glaucoma treatment", quantity: 9 },
  { name: "Carbamazepine", use: "Seizures", quantity: 23 },
  { name: "Sodium Valproate", use: "Epilepsy", quantity: 17 },
  { name: "Phenytoin", use: "Anti-epileptic", quantity: 15 },
  { name: "Levetiracetam", use: "Seizure control", quantity: 21 },
  { name: "Diazepam", use: "Anxiety and seizures", quantity: 20 },
  { name: "Lorazepam", use: "Anxiety", quantity: 12 },
  { name: "Clonazepam", use: "Seizure and panic disorder", quantity: 16 },
  { name: "Haloperidol", use: "Psychosis", quantity: 14 },
  { name: "Olanzapine", use: "Schizophrenia", quantity: 19 },
  { name: "Risperidone", use: "Bipolar disorder", quantity: 18 },
  { name: "Fluoxetine", use: "Depression", quantity: 22 },
  { name: "Sertraline", use: "Depression and anxiety", quantity: 23 },
  { name: "Amitriptyline", use: "Chronic pain and depression", quantity: 20 },
  { name: "Propranolol", use: "Migraine and BP", quantity: 24 },
  { name: "Sumatriptan", use: "Migraine", quantity: 15 },
  { name: "Meclizine", use: "Vertigo and nausea", quantity: 11 },
  { name: "Hyoscine", use: "Motion sickness", quantity: 13 },
  { name: "Loperamide", use: "Diarrhea", quantity: 26 },
  { name: "Rifaximin", use: "Traveler’s diarrhea", quantity: 14 },
  { name: "Simethicone", use: "Gas relief", quantity: 17 },
  { name: "Dicyclomine", use: "Stomach cramps", quantity: 20 },
  { name: "Bismuth Subsalicylate", use: "Upset stomach", quantity: 15 },
  { name: "Lactulose", use: "Constipation", quantity: 18 },
  { name: "Psyllium Husk", use: "Fiber supplement", quantity: 22 },
  { name: "Senna", use: "Laxative", quantity: 19 },
  { name: "Glycerin Suppository", use: "Constipation relief", quantity: 12 },
  { name: "Ornidazole", use: "Amoebic infections", quantity: 13 },
  { name: "Tinidazole", use: "Protozoal infections", quantity: 14 },
  { name: "Fluconazole", use: "Fungal infections", quantity: 20 },
  { name: "Terbinafine", use: "Ringworm", quantity: 17 },
  { name: "Ketoconazole Shampoo", use: "Dandruff", quantity: 10 },
  { name: "Povidone Iodine Gargle", use: "Mouth infections", quantity: 15 },
  { name: "Betamethasone Cream", use: "Skin allergies", quantity: 13 },
  { name: "Calamine Lotion", use: "Skin irritation", quantity: 18 },
  { name: "Mupirocin Ointment", use: "Skin infections", quantity: 19 },
  { name: "Acyclovir", use: "Viral infections", quantity: 20 },
  { name: "Valacyclovir", use: "Herpes treatment", quantity: 17 },
  { name: "Oseltamivir", use: "Influenza", quantity: 11 },
  { name: "Nicotine Patch", use: "Quit smoking", quantity: 8 },
  { name: "Sildenafil", use: "Erectile dysfunction", quantity: 14 },
  { name: "Tamsulosin", use: "Urinary symptoms", quantity: 18 },
  { name: "Finasteride", use: "Hair loss and prostate", quantity: 13 },
  { name: "Methotrexate", use: "Autoimmune disorders", quantity: 16 },
  { name: "Colchicine", use: "Gout", quantity: 12 },
  { name: "Allopurinol", use: "Uric acid control", quantity: 23 },
  { name: "Tacrolimus", use: "Organ transplant", quantity: 9 },
  { name: "Mycophenolate", use: "Immunosuppressant", quantity: 11 },
  { name: "Donepezil", use: "Alzheimer’s", quantity: 8 },
  { name: "Memantine", use: "Dementia", quantity: 10 },
  { name: "Folic Acid", use: "Pregnancy support", quantity: 35 },
  { name: "Vitamin D3", use: "Bone health", quantity: 38 },
  { name: "Biotin", use: "Hair and nails", quantity: 20 },
  { name: "Magnesium Tablets", use: "Muscle health", quantity: 27 },
  { name: "Potassium Chloride", use: "Electrolyte supplement", quantity: 18 },
  { name: "ORS Electrolyte Tablets", use: "Dehydration support", quantity: 32 },
  { name: "Electral Powder", use: "Oral rehydration", quantity: 25 },
  { name: "Isabgol", use: "Natural fiber", quantity: 40 },
  { name: "Ginger Capsules", use: "Nausea and digestion", quantity: 19 },
  { name: "Turmeric Capsules", use: "Anti-inflammatory", quantity: 30 },
];

// Assign unique 4-digit codes
const codes = generateUniqueCodes(baseMedicines.length);
const medicines = baseMedicines.map((med, index) => ({
  ...med,
  medicineCode: codes[index],
}));

async function seedMedicines() {
  try {
    await medicineModel.insertMany(medicines);
    console.log("Medicines inserted successfully!");
    mongoose.disconnect();
  } catch (error) {
    console.error("Error seeding data:", error);
  }
}

seedMedicines();
